'use client';
import {useEffect,useRef,useState} from 'react';
import {LayoutDashboard,Inbox,History,ArrowUpRight,Plus,Search,Download,ChevronRight,Boxes,ShieldCheck,FileSpreadsheet,Clock3,MessageSquare,ArrowLeft,Loader2} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogHeader,DialogFooter} from '@/components/ui/dialog';
import {Textarea} from '@/components/ui/textarea';
import {Toaster,toast} from 'sonner';
import {Choice,ChannelBadge,StatusBadge,Empty} from './business-ui';
import CaseWorkspace from './case-workspace';
import type {AppState,CommercialCase,SystemsData,Channel} from '@/lib/domain/models';
import {STATUSES} from '@/lib/domain/models';
import {loadSystems} from '@/lib/services/excelService';
import {loadState,saveState,exportState} from '@/lib/services/persistence';
import {demoCases} from '@/data/demoCases';
import {operators} from '@/data/catalog';
import {createCase,openCase} from '@/lib/services/caseService';
import {recommendNextAction} from '@/lib/services/responseService';
import {dateKey,dateTime,channelName} from '@/lib/domain/common';
type View='dashboard'|'inbox'|'audit';
export default function Workspace(){
 const [state,setState]=useState<AppState|null>(null);const stateRef=useRef<AppState|null>(null);const [systems,setSystems]=useState<SystemsData|null>(null);const [error,setError]=useState('');const [view,setView]=useState<View>('dashboard');const [selected,setSelected]=useState('');const [search,setSearch]=useState('');const [channel,setChannel]=useState('all');const [status,setStatus]=useState('all');const [owner,setOwner]=useState('all');const [day,setDay]=useState('');const [newOpen,setNewOpen]=useState(false);
 useEffect(()=>{let live=true;loadSystems().then(data=>{if(!live)return;const saved=loadState();const initial=saved||{version:1 as const,revision:0,operatorId:'laura',cases:demoCases(data)};if(!saved)saveState(initial,0);stateRef.current=initial;setSystems(data);setState(initial);}).catch(e=>{if(live)setError(String(e.message||e));});return()=>{live=false;};},[]);
 function commit(next:AppState){const previous=stateRef.current!;const updated={...next,revision:previous.revision+1};saveState(updated,previous.revision);stateRef.current=updated;setState(updated);}
 function changeCase(id:string,fn:(c:CommercialCase)=>CommercialCase){const current=stateRef.current!;commit({...current,cases:current.cases.map(c=>c.id===id?fn(c):c)});}
 function safe(action:()=>void){try{action();}catch(e){toast.error((e as Error).message);}}
 function open(c:CommercialCase){safe(()=>{changeCase(c.id,v=>openCase(v,stateRef.current!.operatorId));setSelected(c.id);});}
 const c=state?.cases.find(c=>c.id===selected);
 const filtered=state?.cases.filter(c=>(channel==='all'||c.initialChannel===channel)&&(status==='all'||c.status===status)&&(owner==='all'||c.assignedOperator===owner)&&(!day||dateKey(c.createdAt)===day)&&`${c.id} ${c.customer} ${c.company} ${c.conversation[0].content} ${c.orderItems.map(i=>i.sku).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[];
 const today=dateKey(new Date().toISOString());const sent=state?.cases.flatMap(c=>c.conversation.filter(m=>m.direction==='OUTBOUND').map(m=>({c,m})))||[];
 const firstResponses=state?.cases.map(c=>({c,m:c.conversation.find(m=>m.direction==='OUTBOUND')})).filter(x=>x.m)||[];
 const mean=firstResponses.length?Math.round(firstResponses.reduce((sum,{c,m})=>sum+(Date.parse(m!.timestamp)-Date.parse(c.createdAt))/60000,0)/firstResponses.length):null;
 const pending=state?.cases.filter(c=>!['RESPONDIDO','CERRADO'].includes(c.status))||[];
 return <SidebarProvider><Sidebar className="nexo-sidebar"><SidebarHeader><a className="brand" href="#" onClick={e=>{e.preventDefault();setSelected('');setView('dashboard');}}><span className="brand-icon"><Boxes size={23}/></span><span>nexo<span className="brand-dot">.</span></span></a><p className="sidebar-caption">GESTIÓN COMERCIAL</p></SidebarHeader><SidebarContent><SidebarMenu>{([{id:'dashboard',label:'Dashboard',icon:LayoutDashboard},{id:'inbox',label:'Bandeja de pedidos',icon:Inbox},{id:'audit',label:'Auditoría',icon:History}] as const).map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id&&!selected} onClick={()=>{setSelected('');setView(n.id);}}><n.icon/><span>{n.label}</span>{n.id==='inbox'&&<span className="nav-count">{pending.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="operator-principle"><ShieldCheck size={23}/><b>La IA asiste.<br/>La persona decide.</b><p>Vos revisás y confirmás cada respuesta.</p></div><span className="local-caption">Demostración · Datos ficticios<br/>Guardado en este navegador</span></SidebarFooter></Sidebar>
 <main className="app-main"><header className="topbar"><div className="topbar-left"><SidebarTrigger/><span>Espacio de trabajo</span><ChevronRight size={15}/><strong>{c?c.id:view==='dashboard'?'Dashboard':view==='inbox'?'Bandeja de pedidos':'Auditoría'}</strong></div><div className="operator-picker"><span>Operador activo</span><Choice label="Operador activo" value={state?.operatorId||'laura'} options={operators.map(o=>({value:o.id,label:o.name}))} onChange={id=>safe(()=>commit({...stateRef.current!,operatorId:id}))}/><div className="avatar">{operators.find(o=>o.id===state?.operatorId)?.name.split(' ').map(x=>x[0]).slice(0,2).join('')||'LG'}</div></div></header>
 {error?<div className="page"><div role="alert" className="error-panel"><h1>No pudimos cargar el espacio</h1><p>{error}</p><p>No se sobrescribieron los datos guardados.</p><Button onClick={()=>location.reload()}>Volver a intentar</Button></div></div>:!state||!systems?<div className="loading"><Loader2 className="spin"/>Leyendo catálogo, stock y precios…</div>:c?<div className="page detail-page"><Button variant="ghost" onClick={()=>{setSelected('');setView('inbox');}}><ArrowLeft size={16}/>Volver a la bandeja</Button><CaseWorkspace key={c.id} c={c} systems={systems} operator={state.operatorId} change={fn=>changeCase(c.id,fn)} reloadSystems={async()=>{const d=await loadSystems();setSystems(d);return d;}}/></div>:<div className="page">
 <div className="page-heading"><div><span className="eyebrow">TU OPERACIÓN, EN UN LUGAR</span><h1>{view==='dashboard'?'Gestión de pedidos':view==='inbox'?'Bandeja de pedidos':'Auditoría comercial'}</h1><p>{view==='dashboard'?'Convertí cada consulta en un próximo paso claro.':view==='inbox'?'Todas las conversaciones, con su contexto y seguimiento.':'Cada decisión, cada cambio y cada respuesta quedan registrados.'}</p></div><div className="heading-actions"><Button variant="outline" onClick={()=>exportState(state)}><Download size={16}/>Exportar historial</Button><Button onClick={()=>setNewOpen(true)}><Plus size={17}/>Nueva consulta</Button></div></div>
 {view==='dashboard'?<><div className="stats-grid">{[
 ['Consultas recibidas hoy',state.cases.filter(c=>dateKey(c.createdAt)===today).length,'Todos los canales'],['Pendientes',pending.length,'Requieren seguimiento'],['Esperando cliente',state.cases.filter(c=>c.status==='ESPERANDO CLIENTE').length,'Próximo paso del cliente'],['Listas para cotizar',state.cases.filter(c=>c.status==='LISTO PARA COTIZAR').length,'Datos obligatorios completos']
 ].map(([title,value,caption],i)=><div className={`metric-card metric-${i}`} key={title}><div className="metric-title">{title}<ArrowUpRight size={17}/></div><strong>{value}</strong><span>{caption}</span></div>)}</div>
 <div className="dashboard-grid"><section className="panel attention-panel"><div className="panel-heading"><div><span className="eyebrow">PRIORIDADES</span><h2>Necesitan tu atención</h2></div><Button variant="ghost" onClick={()=>setView('inbox')}>Ver bandeja <ChevronRight size={16}/></Button></div>{state.cases.filter(c=>c.validation.issues.some(i=>i.blocking)||c.remediations.some(r=>r.status!=='RESUELTA')).slice(0,4).map(c=><button className="attention-row" key={c.id} onClick={()=>open(c)}><div className="company-avatar">{c.company.slice(0,1)}</div><div><strong>{c.company}</strong><span>{c.id} · {c.scenario}</span></div><StatusBadge status={c.status}/><ChevronRight size={17}/></button>)}</section><section className="panel channels-panel"><span className="eyebrow">CANALES DE INGRESO</span><h2>Una sola bandeja</h2>{(['WHATSAPP','EMAIL','PHONE'] as Channel[]).map(ch=>{const count=state.cases.filter(c=>c.initialChannel===ch).length;return <div className="channel-distribution" key={ch}><div><ChannelBadge channel={ch}/><strong>{count}</strong></div><div className="bar-track"><div className={ch.toLowerCase()} style={{width:`${100*count/state.cases.length}%`}}/></div></div>;})}<div className="channel-footnote">{state.cases.length} casos comerciales en seguimiento</div></section></div>
 <div className="secondary-stats"><div><MessageSquare/><span>Con información faltante<strong>{state.cases.filter(c=>!c.validation.canQuote&&c.status!=='CERRADO').length}</strong></span></div><div><ShieldCheck/><span>Respondidas hoy<strong>{new Set(sent.filter(s=>dateKey(s.m.timestamp)===today).map(s=>s.c.id)).size}</strong></span></div><div><Clock3/><span>Promedio de primera respuesta<strong>{mean===null?'Sin envíos':`${mean} min`}</strong></span></div></div>
 <section className="demo-band"><div className="demo-symbol"><Boxes/></div><div><span className="eyebrow">CASO GUIADO</span><h2>De una consulta incompleta a una cotización</h2><p>Metalúrgica Delta necesita rodamientos. Ayudá a completar su solicitud.</p></div><Button onClick={()=>open(state.cases.find(c=>c.id==='REQ-001')!)}>Abrir REQ-001 <ArrowUpRight size={17}/></Button></section>
 <div className="data-links"><FileSpreadsheet size={17}/><span>Fuentes de la demostración</span><a href="/data/stock_productos.xlsx" download>Stock central.xlsx</a><a href="/data/precios_productos.xlsx" download>Lista de precios.xlsx</a></div></>:<>
 <div className="filter-bar"><div className="search-field"><Search size={17}/><Input aria-label="Buscar casos" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar cliente, empresa, SKU o ID…"/></div><Choice label="Filtrar canal" value={channel} onChange={setChannel} options={[{value:'all',label:'Todos los canales'},...Object.entries(channelName).map(([value,label])=>({value,label}))]}/><Choice label="Filtrar estado" value={status} onChange={setStatus} options={[{value:'all',label:'Todos los estados'},...STATUSES.map(value=>({value,label:value}))]}/><Choice label="Filtrar responsable" value={owner} onChange={setOwner} options={[{value:'all',label:'Todos los responsables'},...operators.map(o=>({value:o.id,label:o.name}))]}/><Input aria-label="Filtrar fecha" type="date" value={day} onChange={e=>setDay(e.target.value)}/><Button variant="ghost" onClick={()=>{setSearch('');setChannel('all');setStatus('all');setOwner('all');setDay('');}}>Limpiar</Button></div>
 <section className="panel table-panel"><div className="table-caption"><strong>{filtered.length} casos</strong><span>{view==='audit'?'Seleccioná un caso para ver su cronología completa.':'Una consulta, un caso. El historial siempre se conserva.'}</span></div><Table><TableHeader><TableRow>{(view==='inbox'?['Solicitud / ingreso','Cliente / empresa','Resumen','Productos','Estado','Responsable','Próxima acción']:['Caso / cliente','Empresa','Ingreso','Respuesta','Operador de envío','Tiempo primera respuesta','Estado']).map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{filtered.map(c=>{const outbound=c.conversation.filter(m=>m.direction==='OUTBOUND');const last=outbound.at(-1);return <TableRow key={c.id} className="click-row" onClick={()=>open(c)}>{view==='inbox'?<><TableCell><button className="id-link" onClick={e=>{e.stopPropagation();open(c);}}>{c.id}</button><ChannelBadge channel={c.initialChannel}/><small>{dateTime(c.createdAt)}</small></TableCell><TableCell><strong>{c.company||'Empresa no informada'}</strong><small>{c.customer||'Cliente no informado'}</small></TableCell><TableCell className="summary-cell"><p>{c.conversation[0].content}</p></TableCell><TableCell>{c.orderItems.length}</TableCell><TableCell><StatusBadge status={c.status}/>{c.remediations.some(r=>r.status!=='RESUELTA')&&<small className="warning-text">Pendiente de precio</small>}</TableCell><TableCell>{operators.find(o=>o.id===c.assignedOperator)?.name}</TableCell><TableCell className="next-cell">{recommendNextAction(c).title}<ArrowUpRight size={15}/></TableCell></>:<><TableCell><button className="id-link">{c.id}</button><small>{c.customer}</small></TableCell><TableCell>{c.company}</TableCell><TableCell><ChannelBadge channel={c.initialChannel}/><small>{dateTime(c.createdAt)}</small></TableCell><TableCell>{last?<><ChannelBadge channel={last.channel}/><small>{dateTime(last.timestamp)}</small></>:'Sin envío'}</TableCell><TableCell>{operators.find(o=>o.id===last?.operatorId)?.name||'—'}</TableCell><TableCell>{outbound[0]?`${Math.round((Date.parse(outbound[0].timestamp)-Date.parse(c.createdAt))/60000)} min`:'—'}</TableCell><TableCell><StatusBadge status={c.status}/></TableCell></>}</TableRow>;})}</TableBody></Table>{!filtered.length&&<Empty>No hay casos que coincidan con los filtros.</Empty>}</section></>}
 </div>}
 </main><Toaster richColors position="bottom-right"/><Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>Nueva consulta comercial</DialogTitle><DialogDescription>Simulá un mensaje recibido. La extracción se ejecutará al crear el caso.</DialogDescription></DialogHeader>{state&&systems&&<NewCaseForm onSave={input=>{safe(()=>{const curr=stateRef.current!;const max=Math.max(...curr.cases.map(c=>Number(c.id.replace('REQ-',''))||0));const next=createCase({...input,id:`REQ-${String(max+1).padStart(3,'0')}`},systems,curr.operatorId);commit({...curr,cases:[next,...curr.cases]});setNewOpen(false);setView('inbox');setSelected(next.id);});}}/>}</DialogContent></Dialog></SidebarProvider>;
}
function NewCaseForm({onSave}:{onSave:(input:{channel:Channel;content:string;customer:string;company:string;email:string;phone:string;subject:string})=>void}){
 const [fields,setFields]=useState({customer:'',company:'',email:'',phone:'',subject:'Solicitud de cotización',content:'',channel:'WHATSAPP' as Channel});
 return <form onSubmit={e=>{e.preventDefault();onSave(fields);}}><div className="form-grid"><label>Canal<Choice label="Canal inicial" value={fields.channel} onChange={v=>setFields({...fields,channel:v as Channel})} options={Object.entries(channelName).map(([value,label])=>({value,label}))}/></label>{(['customer','company','email','phone'] as const).map((k,i)=><label key={k}>{['Cliente','Empresa','Email','Teléfono'][i]}<Input value={fields[k]} onChange={e=>setFields({...fields,[k]:e.target.value})}/></label>)}{fields.channel==='EMAIL'&&<label>Asunto<Input value={fields.subject} onChange={e=>setFields({...fields,subject:e.target.value})}/></label>}</div><label>Mensaje / transcripción<Textarea required minLength={4} value={fields.content} onChange={e=>setFields({...fields,content:e.target.value})} rows={5} placeholder="Necesitamos 20 motores MTR-200…"/></label><DialogFooter><Button type="submit">Crear y analizar solicitud</Button></DialogFooter></form>;
}
